name: NPM Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - name: Build protobuf library
        run: |
          git clone https://github.com/protocolbuffers/protobuf.git
          cd protobuf
          git submodule update --init --recursive
          ./autogen.sh
          ./autogen.sh
          ./configure
          make
          make check
          sudo make install
          sudo ldconfig
      - uses: actions/checkout@v2
        with:
          submodules: recursive 
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm run update

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive 
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm run update
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}