name: NPM Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - name: Build protobuf library
        run: sudo apt-get install -y protobuf-compiler
      - uses: actions/checkout@v2
        with:
          submodules: recursive 
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm run update

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive 
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm run update
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}